apiVersion: v1
kind: ConfigMap
metadata:
  name: toggly-controller-config
  namespace: {{ .Values.namespace }}
  labels:
    app: toggly
    app.kubernetes.io/name: toggly-controller
data:
  configuration.yaml: |
{{- $config := .Values.controller.config | default dict }}
    storageStrategy: {{ $config.storeProvider | default "inMemory" }}
    {{- if $config.mysql }}
    mysql:
      {{ $config.mysql }}
    {{- end }}
    {{- if $config.redis }}
    redis:
      {{ $config.redis }}
    {{- end }}
    {{- if $config.postgres }}
    postgres:
      {{ $config.postgres }}
    {{- end }}