{{- if eq .Values.deploymentType "individual" }}
apiVersion: v1
kind: Service
metadata:
  name: toggly-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: toggly
    app.kubernetes.io/name: toggly
    app.kubernetes.io/component: toggly-ui
  annotations:
    toggly.io/api-spec: https://github.com/pabloubal/toggly-ui
    toggly.io/api-type: rest
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{.Values.ui.port}}
    targetPort: ui-port
  selector:
    app.kubernetes.io/name: toggly
    app.kubernetes.io/instance: toggly-ui
  type: NodePort
{{- end }}
---
{{- if eq .Values.deploymentType "all-in-one" }}
apiVersion: v1
kind: Service
metadata:
  name: toggly-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: toggly
    app.kubernetes.io/name: toggly
    app.kubernetes.io/component: toggly-ui
  annotations:
    toggly.io/api-spec: https://github.com/pabloubal/toggly-ui
    toggly.io/api-type: rest
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{.Values.ui.port}}
    targetPort: ui-port
  selector:
    app.kubernetes.io/name: toggly
    app.kubernetes.io/component: all-in-one
  type: NodePort
{{- end }}